language: go

go:
  - 1.3
  - 1.4

services:
  - redis-server
  - cassandra
  - mongodb
  - neo4j
  - rabbitmq

install:
  - go get -v ./...
  - go get github.com/stretchr/testify/assert
  - export PATH=$PATH:$HOME/gopath/bin

script:
  - go test -v ./penlook/...