language: go

go:
  - 1.4

services:
  - redis-server
  - mongodb

env:
  - AMQP_URL=amqp://guest:guest@127.0.0.1:5672/ GOMAXPROCS=2

install:
  - go get -v ./...
  - go get github.com/stretchr/testify/assert
  - export PATH=$PATH:$HOME/gopath/bin

before_script:
  - git submodule update --recursive
  - git submodule status
  - git submodule foreach git checkout master
  - mysql -e 'create database test;'
  - sudo chmod +x ./service.sh
  - git clone https://github.com/penlook/test.git
  - (sudo pip install redis && sudo pip install pyyaml)
  - (cd test; python build.py)

script:
  - ./service.sh api build start test
  - ./service.sh socket build start test
  - ./service.sh storage build start test