language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - tips

services:
  - redis-server
  - cassandra
  - mongodb

install:
  - go get -v ./...
  - go get github.com/stretchr/testify/assert
  - export PATH=$PATH:$HOME/gopath/bin

script:
  - go test -v ./penlook/...