language: go

go:
  - 1.4

services:
  - redis-server
  - mongodb

env:
  global:
    - AWS_S3_REGION="ap-northeast-1"
    - AWS_S3_BUCKET="penlook-abc"
    - secure: "NnrWhxR3eu1/Iq9nxcEgER9WhG2cTXGX0ZHyduRvOOHW2GFclT7vtDnTnH5t2+fAYOdhOTPKm3vEBjrnMoR+UZZIbKfYQTyEYpAu4QfAECA/dj62K2NMU8fdhi2+raUbHhErUPAngFTc7XWsxzoEBgHmr2YT7oBtZdTd559mEbA="
    - secure: "RhNnCFpexFK1rYzbmFHZcSbl3k8W929mMq4fEH20gYV6MgMZYbRsJnZLYNXOEQ2iIzbkIIcGY2oS/V0QlzQS/tpgGQnd/pEsM5OEsW8h+S0RpmplOKV6q+7b1LDDLnw2fClen0RW3piWA3SHRAmotLGY0uhehQ/mqiL/kRLqUyM="

install:
  - go get -v ./...
  - go get github.com/stretchr/testify/assert
  - export PATH=$PATH:$HOME/gopath/bin
  - git submodule update --recursive
  - git submodule status
  - git submodule foreach git checkout master
  - mysql -e 'create database test;'
  - sudo chmod +x ./service.sh
  - git clone https://github.com/penlook/test.git
  - (sudo pip install redis && sudo pip install pyyaml)
  - (cd test; python build.py)
  - chmod +x ./service.sh
  - ./service.sh api build start
  - ./service.sh socket build start
  - ./service.sh storage build start

script:
  - ./service.sh api test
  - ./service.sh socket test
  - ./service.sh storage test